import type {
  ComponentCategory,
  ComponentDefinition,
  ComponentType,
} from "./types";

// ─── Component Catalog ────────────────────────────────────────────────────
// 28+ component definitions organized into Core (18), Advanced (7), and Layout (4) groups.

export const COMPONENT_CATALOG: ComponentDefinition[] = [
  // ─── CORE (18) ────────────────────────────────────────────────────────────

  {
    type: "short-text",
    category: "core",
    name: "Short Text",
    description: "Single-line text input for brief responses",
    icon: "Type",
    accent: "blue",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "paragraph",
    category: "core",
    name: "Paragraph",
    description: "Multi-line text area for longer responses",
    icon: "AlignLeft",
    accent: "blue",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "alphanumeric",
    category: "core",
    name: "Alphanumeric",
    description: "Text input restricted to letters and numbers",
    icon: "Hash",
    accent: "teal",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "number",
    category: "core",
    name: "Number",
    description: "Numeric input with optional min/max and decimals",
    icon: "Calculator",
    accent: "pink",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "dropdown",
    category: "core",
    name: "Dropdown",
    description: "Single-select dropdown list of options",
    icon: "ChevronDown",
    accent: "blue",
    supportsOptions: true,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "multi-select",
    category: "core",
    name: "Multi Select",
    description: "Choose multiple options from a list",
    icon: "ListChecks",
    accent: "blue",
    supportsOptions: true,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "radio",
    category: "core",
    name: "Radio",
    description: "Single-select from visible radio button options",
    icon: "Circle",
    accent: "pink",
    supportsOptions: true,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "checkbox",
    category: "core",
    name: "Checkbox",
    description: "Multi-select from visible checkbox options",
    icon: "CheckSquare",
    accent: "pink",
    supportsOptions: true,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "toggle",
    category: "core",
    name: "Toggle",
    description: "On/off switch with configurable labels",
    icon: "ToggleLeft",
    accent: "blue",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "image-capture",
    category: "core",
    name: "Image Capture",
    description: "Capture photos from camera or gallery",
    icon: "Camera",
    accent: "amber",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "date-picker",
    category: "core",
    name: "Date Picker",
    description: "Date selection with optional constraints",
    icon: "Calendar",
    accent: "amber",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "time-range",
    category: "core",
    name: "Time Range",
    description: "Capture start and end time values",
    icon: "Clock",
    accent: "amber",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "gps-location",
    category: "core",
    name: "GPS Location",
    description: "Capture device GPS coordinates",
    icon: "MapPin",
    accent: "green",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "geo-fencing",
    category: "core",
    name: "Geo-fencing",
    description: "Validate location within a defined radius",
    icon: "Target",
    accent: "green",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "signature",
    category: "core",
    name: "Signature",
    description: "Capture handwritten signature on screen",
    icon: "PenTool",
    accent: "purple",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "rating",
    category: "core",
    name: "Rating / Stars",
    description: "Star-based rating input",
    icon: "Star",
    accent: "amber",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "email",
    category: "core",
    name: "Email",
    description: "Email address input with format validation",
    icon: "Mail",
    accent: "blue",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },
  {
    type: "phone",
    category: "core",
    name: "Phone",
    description: "Phone number input with format validation",
    icon: "Phone",
    accent: "blue",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: true,
  },

  // ─── ADVANCED (7) ─────────────────────────────────────────────────────────

  {
    type: "barcode-qr",
    category: "advanced",
    name: "Barcode / QR",
    description: "Scan barcode or QR code using device camera",
    icon: "QrCode",
    accent: "purple",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "calculation",
    category: "advanced",
    name: "Calculation",
    description: "Auto-calculated field using a formula on other fields",
    icon: "Sigma",
    accent: "teal",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: true,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "dependent-dropdown",
    category: "advanced",
    name: "Dependent DD",
    description: "Dropdown whose options depend on a parent field value",
    icon: "GitBranch",
    accent: "blue",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: true,
    supportsPrefill: false,
  },
  {
    type: "list-view",
    category: "advanced",
    name: "List View",
    description: "Tabular data entry with configurable columns",
    icon: "Table",
    accent: "teal",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: true,
    supportsPrefill: false,
  },
  {
    type: "file-upload",
    category: "advanced",
    name: "File Upload",
    description: "Upload documents with type and size restrictions",
    icon: "Upload",
    accent: "amber",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "conditional-logic",
    category: "advanced",
    name: "Conditional Logic",
    description: "Show or hide fields based on conditions",
    icon: "GitMerge",
    accent: "purple",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },

  // ─── LAYOUT (4) ───────────────────────────────────────────────────────────

  {
    type: "section-group",
    category: "layout",
    name: "Section Group",
    description: "Group related fields under a collapsible section",
    icon: "Layers",
    accent: "purple",
    supportsOptions: false,
    supportsChildren: true,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "add-more-block",
    category: "layout",
    name: "Add More Block",
    description: "Repeatable block of fields the user can add more of",
    icon: "PlusCircle",
    accent: "amber",
    supportsOptions: false,
    supportsChildren: true,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "divider",
    category: "layout",
    name: "Divider",
    description: "Visual separator between form sections",
    icon: "Minus",
    accent: "gray",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
  {
    type: "info-label",
    category: "layout",
    name: "Info / Label",
    description: "Static text or instructional label on the form",
    icon: "Info",
    accent: "gray",
    supportsOptions: false,
    supportsChildren: false,
    supportsFormula: false,
    supportsDataSource: false,
    supportsPrefill: false,
  },
];

// ─── Helper Functions ─────────────────────────────────────────────────────

/**
 * Returns all component definitions for a given category.
 */
export function getComponentsByCategory(
  category: ComponentCategory
): ComponentDefinition[] {
  return COMPONENT_CATALOG.filter(
    (component) => component.category === category
  );
}

/**
 * Returns the component definition for a given component type, or undefined if not found.
 */
export function getComponentDefinition(
  type: ComponentType
): ComponentDefinition | undefined {
  return COMPONENT_CATALOG.find((component) => component.type === type);
}
