/**
 * Mock data for Form Builder Configuration Suite.
 * Provides 2 sample FormConfiguration objects with pre-populated fields.
 */

import type { FormConfiguration, FormField } from "./types";

// ─── Helper: Create a default FormField ───────────────────────────────────

function createField(
  overrides: Partial<FormField> & Pick<FormField, "id" | "type" | "label" | "order">
): FormField {
  return {
    helpText: "",
    parentId: null,
    visibility: "always",
    visibilityRules: [],
    readOnly: false,
    prefillSource: null,
    prefillField: "",
    prefillCustomValue: "",
    required: "no",
    requiredRules: [],
    typeConfig: {},
    optionsSource: null,
    manualOptions: [],
    excelOptionsCount: 0,
    masterEntity: "",
    masterField: "",
    mappingParentField: "",
    dataSource: null,
    formula: "",
    formulaResultFormat: "number",
    sectionLabel: "",
    addMoreLabel: "",
    addMoreMin: 1,
    addMoreMax: 5,
    toggleOnLabel: "Yes",
    toggleOffLabel: "No",
    conditionAction: "show",
    conditionRules: [],
    ...overrides,
  };
}

// ─── Config 1: "All 28 Components — Sequential Demo" ─────────────────────

const config1Fields: FormField[] = [
  createField({
    id: "f1-001",
    type: "short-text",
    label: "Customer Name",
    helpText: "Enter the full name of the customer",
    order: 0,
    required: "always",
    typeConfig: { maxLength: 100 },
  }),
  createField({
    id: "f1-002",
    type: "paragraph",
    label: "Visit Notes",
    helpText: "Describe the purpose and outcome of the visit",
    order: 1,
    typeConfig: { maxLength: 500 },
  }),
  createField({
    id: "f1-003",
    type: "alphanumeric",
    label: "Store Code",
    helpText: "Alphanumeric store identifier (e.g., STR-001)",
    order: 2,
    required: "always",
    typeConfig: { minLength: 3, maxLength: 20 },
  }),
  createField({
    id: "f1-004",
    type: "number",
    label: "Units Sold",
    helpText: "Number of units sold during the visit",
    order: 3,
    typeConfig: { minValue: 0, maxValue: 10000, decimals: 0 },
  }),
  createField({
    id: "f1-005",
    type: "dropdown",
    label: "Customer Tier",
    helpText: "Select the customer tier level",
    order: 4,
    optionsSource: "manual",
    manualOptions: ["Platinum", "Gold", "Silver", "Bronze"],
  }),
  createField({
    id: "f1-006",
    type: "multi-select",
    label: "Product Categories",
    helpText: "Select all applicable product categories",
    order: 5,
    optionsSource: "manual",
    manualOptions: ["Beverages", "Snacks", "Personal Care", "Household", "Dairy"],
  }),
  createField({
    id: "f1-007",
    type: "radio",
    label: "Payment Mode",
    helpText: "Select the payment method used",
    order: 6,
    optionsSource: "manual",
    manualOptions: ["Cash", "Card", "UPI", "Credit"],
  }),
  createField({
    id: "f1-008",
    type: "checkbox",
    label: "Compliance Checks",
    helpText: "Mark all checks completed",
    order: 7,
    optionsSource: "manual",
    manualOptions: ["Planogram verified", "Stock counted", "Pricing correct", "Display updated"],
  }),
  createField({
    id: "f1-009",
    type: "toggle",
    label: "Store Open",
    helpText: "Is the store currently open for business?",
    order: 8,
    toggleOnLabel: "Open",
    toggleOffLabel: "Closed",
  }),
  createField({
    id: "f1-010",
    type: "image-capture",
    label: "Shelf Photo",
    helpText: "Capture a photo of the product shelf display",
    order: 9,
    required: "always",
    typeConfig: { captureMode: "live", minPhotos: 1, maxPhotos: 5, watermark: true },
  }),
  createField({
    id: "f1-011",
    type: "date-picker",
    label: "Visit Date",
    helpText: "Date of the store visit",
    order: 10,
    required: "always",
    typeConfig: { defaultToday: true, allowPast: true, maxBackdateDays: 7, allowFuture: false },
  }),
  createField({
    id: "f1-012",
    type: "time-range",
    label: "Visit Duration",
    helpText: "Start and end time of the visit",
    order: 11,
    typeConfig: { timeFormat: "12h" },
  }),
  createField({
    id: "f1-013",
    type: "gps-location",
    label: "Store Location",
    helpText: "Capture GPS coordinates of the store",
    order: 12,
  }),
  createField({
    id: "f1-014",
    type: "geo-fencing",
    label: "Store Geo-fence",
    helpText: "Verify presence within store boundary",
    order: 13,
    typeConfig: { radiusMeters: 200, latLongSource: "store-master" },
  }),
  createField({
    id: "f1-015",
    type: "signature",
    label: "Customer Signature",
    helpText: "Collect customer signature for delivery confirmation",
    order: 14,
  }),
  createField({
    id: "f1-016",
    type: "rating",
    label: "Service Rating",
    helpText: "Rate the overall service quality",
    order: 15,
    typeConfig: { maxStars: 5 },
  }),
  createField({
    id: "f1-017",
    type: "email",
    label: "Contact Email",
    helpText: "Store manager's email address",
    order: 16,
  }),
  createField({
    id: "f1-018",
    type: "phone",
    label: "Contact Phone",
    helpText: "Store manager's phone number",
    order: 17,
  }),
  createField({
    id: "f1-019",
    type: "barcode-qr",
    label: "Product Barcode",
    helpText: "Scan the product barcode for identification",
    order: 18,
    typeConfig: { codeType: "any", validateAgainstMaster: true },
  }),
  createField({
    id: "f1-020",
    type: "calculation",
    label: "Total Revenue",
    helpText: "Automatically calculated from units × price",
    order: 19,
    formula: "{f1-004} * 150",
    formulaResultFormat: "currency",
  }),
  createField({
    id: "f1-021",
    type: "dependent-dropdown",
    label: "Product Sub-category",
    helpText: "Depends on the selected product category",
    order: 20,
    dataSource: {
      source: "product-master",
      customName: "",
      chainLevels: ["Category", "Sub-category"],
      filterColumns: [],
      readOnlyColumns: [],
      editableColumns: [],
    },
  }),
  createField({
    id: "f1-022",
    type: "list-view",
    label: "Stock Audit Table",
    helpText: "Review and update stock quantities",
    order: 21,
    dataSource: {
      source: "product-master",
      customName: "",
      chainLevels: [],
      filterColumns: ["SKU", "Product Name"],
      readOnlyColumns: ["SKU", "Product Name", "MRP"],
      editableColumns: [
        { name: "Quantity", type: "number", required: true, min: 0, max: 9999 },
        { name: "Expiry Date", type: "date", required: false },
      ],
    },
  }),
  createField({
    id: "f1-023",
    type: "file-upload",
    label: "Invoice Upload",
    helpText: "Upload the purchase invoice",
    order: 22,
    typeConfig: { allowedFileTypes: ["pdf", "jpg", "png"], maxFileSize: 10, maxFileCount: 3 },
  }),
  createField({
    id: "f1-024",
    type: "conditional-logic",
    label: "Show Premium Section",
    helpText: "Display premium fields when Customer Tier is Platinum",
    order: 23,
    conditionAction: "show",
    conditionRules: [
      { id: "cr-001", sourceFieldId: "f1-005", operator: "equals", value: "Platinum" },
    ],
  }),
  createField({
    id: "f1-025",
    type: "section-group",
    label: "Order Details",
    helpText: "",
    order: 24,
    sectionLabel: "Order Details",
  }),
  createField({
    id: "f1-026",
    type: "short-text",
    label: "Order ID",
    helpText: "Enter the purchase order number",
    order: 25,
    parentId: "f1-025",
    required: "always",
  }),
  createField({
    id: "f1-027",
    type: "number",
    label: "Order Amount",
    helpText: "Total order value in ₹",
    order: 26,
    parentId: "f1-025",
    typeConfig: { minValue: 0, decimals: 2 },
  }),
  createField({
    id: "f1-028",
    type: "add-more-block",
    label: "Competitor Products",
    helpText: "",
    order: 27,
    addMoreLabel: "Add Competitor Product",
    addMoreMin: 1,
    addMoreMax: 10,
  }),
  createField({
    id: "f1-029",
    type: "short-text",
    label: "Competitor Brand",
    helpText: "Name of the competitor brand",
    order: 28,
    parentId: "f1-028",
  }),
  createField({
    id: "f1-030",
    type: "number",
    label: "Competitor Price",
    helpText: "Price of the competitor product",
    order: 29,
    parentId: "f1-028",
    typeConfig: { minValue: 0, decimals: 2 },
  }),
  createField({
    id: "f1-031",
    type: "divider",
    label: "Divider",
    order: 30,
  }),
  createField({
    id: "f1-032",
    type: "info-label",
    label: "Important: Please verify all entries before submitting.",
    order: 31,
  }),
];

const config1: FormConfiguration = {
  id: "config-1",
  name: "All 28 Components — Sequential Demo",
  designations: ["ISP Executive", "Team Lead"],
  editPermission: "editable",
  editWindow: "custom-hours",
  editWindowHours: 36,
  fields: config1Fields,
  status: "published",
  createdAt: "2025-01-15T10:00:00Z",
  updatedAt: "2025-01-15T10:00:00Z",
};

// ─── Config 2: "New Form" ─────────────────────────────────────────────────

const config2Fields: FormField[] = [
  createField({
    id: "f2-001",
    type: "short-text",
    label: "Retailer Name",
    helpText: "Full name of the retail outlet",
    order: 0,
    required: "always",
    typeConfig: { maxLength: 150 },
  }),
  createField({
    id: "f2-002",
    type: "alphanumeric",
    label: "Outlet Code",
    helpText: "Unique outlet identifier",
    order: 1,
    required: "always",
    typeConfig: { minLength: 4, maxLength: 12 },
  }),
  createField({
    id: "f2-003",
    type: "dropdown",
    label: "Region",
    helpText: "Select the operating region",
    order: 2,
    optionsSource: "manual",
    manualOptions: ["North", "South", "East", "West", "Central"],
  }),
  createField({
    id: "f2-004",
    type: "dropdown",
    label: "Channel Type",
    helpText: "Distribution channel classification",
    order: 3,
    optionsSource: "manual",
    manualOptions: ["General Trade", "Modern Trade", "E-Commerce", "Institutional"],
  }),
  createField({
    id: "f2-005",
    type: "number",
    label: "Monthly Target",
    helpText: "Monthly sales target in units",
    order: 4,
    typeConfig: { minValue: 0, maxValue: 100000, decimals: 0 },
  }),
  createField({
    id: "f2-006",
    type: "number",
    label: "Achievement %",
    helpText: "Percentage of target achieved",
    order: 5,
    typeConfig: { minValue: 0, maxValue: 200, decimals: 1 },
  }),
  createField({
    id: "f2-007",
    type: "multi-select",
    label: "Brands Stocked",
    helpText: "Select all brands available at this outlet",
    order: 6,
    optionsSource: "manual",
    manualOptions: ["Brand A", "Brand B", "Brand C", "Brand D", "Brand E"],
  }),
  createField({
    id: "f2-008",
    type: "radio",
    label: "Outlet Size",
    helpText: "Size classification of the outlet",
    order: 7,
    optionsSource: "manual",
    manualOptions: ["Small", "Medium", "Large", "Enterprise"],
  }),
  createField({
    id: "f2-009",
    type: "toggle",
    label: "Active Account",
    helpText: "Is this an active trading account?",
    order: 8,
    toggleOnLabel: "Active",
    toggleOffLabel: "Inactive",
  }),
  createField({
    id: "f2-010",
    type: "image-capture",
    label: "Storefront Photo",
    helpText: "Capture a photo of the store entrance",
    order: 9,
    typeConfig: { captureMode: "both", minPhotos: 1, maxPhotos: 3, watermark: true },
  }),
  createField({
    id: "f2-011",
    type: "date-picker",
    label: "Last Order Date",
    helpText: "Date of the most recent order placed",
    order: 10,
    typeConfig: { defaultToday: false, allowPast: true, maxBackdateDays: 30, allowFuture: false },
  }),
  createField({
    id: "f2-012",
    type: "time-range",
    label: "Operating Hours",
    helpText: "Store opening and closing time",
    order: 11,
    typeConfig: { timeFormat: "12h" },
  }),
  createField({
    id: "f2-013",
    type: "gps-location",
    label: "Outlet Coordinates",
    helpText: "GPS location of the outlet",
    order: 12,
  }),
  createField({
    id: "f2-014",
    type: "geo-fencing",
    label: "Outlet Boundary",
    helpText: "Verify field rep is at the outlet",
    order: 13,
    typeConfig: { radiusMeters: 150, latLongSource: "store-master" },
  }),
  createField({
    id: "f2-015",
    type: "signature",
    label: "Owner Signature",
    helpText: "Signature of the outlet owner for agreement",
    order: 14,
  }),
  createField({
    id: "f2-016",
    type: "rating",
    label: "Display Quality",
    helpText: "Rate the product display quality (1-5)",
    order: 15,
    typeConfig: { maxStars: 5 },
  }),
  createField({
    id: "f2-017",
    type: "email",
    label: "Owner Email",
    helpText: "Outlet owner's email address",
    order: 16,
  }),
  createField({
    id: "f2-018",
    type: "phone",
    label: "Owner Phone",
    helpText: "Outlet owner's contact number",
    order: 17,
  }),
  createField({
    id: "f2-019",
    type: "checkbox",
    label: "Promotional Materials",
    helpText: "Select all promotional items placed",
    order: 18,
    optionsSource: "manual",
    manualOptions: ["Banner", "Poster", "Standee", "Shelf Talker", "Wobbler"],
  }),
  createField({
    id: "f2-020",
    type: "paragraph",
    label: "Feedback",
    helpText: "Any additional feedback from the retailer",
    order: 19,
    typeConfig: { maxLength: 1000 },
  }),
  createField({
    id: "f2-021",
    type: "barcode-qr",
    label: "Scheme QR Code",
    helpText: "Scan the promotional scheme QR code",
    order: 20,
    typeConfig: { codeType: "qr", validateAgainstMaster: false },
  }),
  createField({
    id: "f2-022",
    type: "calculation",
    label: "Fill Rate %",
    helpText: "Calculated fill rate based on target and achievement",
    order: 21,
    formula: "({f2-006} / 100) * {f2-005}",
    formulaResultFormat: "percentage",
  }),
  createField({
    id: "f2-023",
    type: "dependent-dropdown",
    label: "Sub-Region",
    helpText: "Sub-region based on selected region",
    order: 22,
    dataSource: {
      source: "store-master",
      customName: "",
      chainLevels: ["Region", "Sub-Region"],
      filterColumns: [],
      readOnlyColumns: [],
      editableColumns: [],
    },
  }),
  createField({
    id: "f2-024",
    type: "list-view",
    label: "Order Line Items",
    helpText: "Enter order details per product",
    order: 23,
    dataSource: {
      source: "product-master",
      customName: "",
      chainLevels: [],
      filterColumns: ["SKU", "Product"],
      readOnlyColumns: ["SKU", "Product", "Price"],
      editableColumns: [
        { name: "Qty", type: "number", required: true, min: 1, max: 999 },
        { name: "Discount %", type: "number", required: false, min: 0, max: 100 },
      ],
    },
  }),
  createField({
    id: "f2-025",
    type: "file-upload",
    label: "Supporting Documents",
    helpText: "Upload any supporting documents",
    order: 24,
    typeConfig: { allowedFileTypes: ["pdf", "docx", "xlsx"], maxFileSize: 5, maxFileCount: 5 },
  }),
  createField({
    id: "f2-026",
    type: "conditional-logic",
    label: "Show Premium Tier Fields",
    helpText: "Display fields for large/enterprise outlets",
    order: 25,
    conditionAction: "show",
    conditionRules: [
      { id: "cr-002", sourceFieldId: "f2-008", operator: "equals", value: "Large" },
    ],
  }),
  createField({
    id: "f2-027",
    type: "section-group",
    label: "Inventory Section",
    helpText: "",
    order: 26,
    sectionLabel: "Inventory Section",
  }),
  createField({
    id: "f2-028",
    type: "number",
    label: "Opening Stock",
    helpText: "Stock at the beginning of the day",
    order: 27,
    parentId: "f2-027",
    typeConfig: { minValue: 0, decimals: 0 },
  }),
  createField({
    id: "f2-029",
    type: "number",
    label: "Closing Stock",
    helpText: "Stock at the end of the day",
    order: 28,
    parentId: "f2-027",
    typeConfig: { minValue: 0, decimals: 0 },
  }),
  createField({
    id: "f2-030",
    type: "divider",
    label: "Divider",
    order: 29,
  }),
  createField({
    id: "f2-031",
    type: "info-label",
    label: "Reminder: Submit before end of shift.",
    order: 30,
  }),
];

const config2: FormConfiguration = {
  id: "config-2",
  name: "New Form",
  designations: [],
  editPermission: "editable",
  editWindow: "custom-hours",
  editWindowHours: 24,
  fields: config2Fields,
  status: "draft",
  createdAt: "2025-01-16T10:00:00Z",
  updatedAt: "2025-01-16T10:00:00Z",
};

// ─── Exported Mock Configurations ─────────────────────────────────────────

export const MOCK_CONFIGURATIONS: FormConfiguration[] = [config1, config2];

// ─── Default fields for a newly created configuration ─────────────────────

export function getDefaultFields(): FormField[] {
  return [
    createField({
      id: crypto.randomUUID(),
      type: "short-text",
      label: "Full Name",
      helpText: "Enter the person's full name",
      order: 0,
      required: "always",
    }),
    createField({
      id: crypto.randomUUID(),
      type: "phone",
      label: "Phone Number",
      helpText: "Primary contact number",
      order: 1,
    }),
    createField({
      id: crypto.randomUUID(),
      type: "date-picker",
      label: "Date",
      helpText: "Select the date",
      order: 2,
      typeConfig: { defaultToday: true },
    }),
  ];
}
